### PR TITLE
Go to IAT and EAT

### PR DESCRIPTION
**Pull request by torusrxxx**
You can use "ntdll:pe.eat" in the go to dialog to go to its EAT. Various other fields in the PE header is also supported. It does not support adding dynamic labels there. Please allow me to access this repository directly.

### CODE REVIEW

**Comment by mrexodia** [comment]
I enabled write access for the developers team, you should be able to
access it now.

**Comment by torusrxxx** [comment]
What do you think of this patch?

**Comment by mrexodia** [comment]
Yeah, looks good to me!

**Comment by mrexodia** [comment]
Thanks!

**Pull request merged**
